train_type: none
checkpoint_settings:
  keep_checkpoints: 5
  interval: 3000
hyperparameters:
  learning_rate: 0.0003
  momentum: 0.9
  num_epoch: 5
use_tune: True
tune:
  run_id: tune_test_1
  learning_rate: 
    way: xxx
    range: 0.003
  momentum: 
    way: yyy
    range: 0.9